name: Build & Synchronization

on:
  push:
    branches:
      - 'master'
      - 'syncimage'
  pull_request:
    branches:
      - 'master'
  page_build:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check pr is properly formatted
        run: diff -u <(echo -n) <(gofmt -d ./pkg ./cmd)

      - name: Downloading go dependencies
        run: go mod vendor

      - name: Build
        run: make

      - name: Synchronization
        env:
          AUTH: ${{ secrets.AUTH }}
          COMMITID: ${{ github.sha}}
        # if: github.event_name == 'push'
        run: echo "$AUTH" > ./auth.json && .github/workflows/sync.sh